#+TITLE: rcouch

Experimental, not working..

Image based on  debian:wheezy

This will build an image that runs [[https://github.com/rcouch/rcouch][rcouch]], a variant of CouchDB,

* Changes from Apache CouchDB 

Copied from the [[https://github.com/Michieljoris/Dockerfiles/tree/master/rcouch][wiki]]:

- Refactoring of the codebase with a new release system based on Erlang reltools
  and rebar, a separations of the applications allowing more custumisations and
  an improved statibiliy of CouchDB (better supervision). With this refactoring
  A release can be fully relocatable and is statically linked.

- View changes - Rcouch offers you the possibility to get incremental view
  changes (ie using the changes API over a view index. View changes can be
  filtered using a javascript function or using the view parameters (you can get
  view changes for a key or a range).

- View-based replication - You can incrementally replicate your documents using
  a view to filter them. This replication is based on the view changes

- Include deleted documents in view results

- Validate documents on read - Validate if the document can be read by the
  current user.

- Write-only databases - Only admins and some readers are able to read a
  database.

- Filter returned fields in changes results

- Improved logging - new logging system using Lager with more granularity in
  logs

- More stats - more statistics in rcouch

- Some Optimisations and internal changes in the source code. This changes has
  been added upon the time to fix issues or optimize some processing based on
  the user and customers feedback.

- Custom extensions - It is easy to add custom extensions to your build using
  the rcouch system. Extensions built-in for rcouch are _random_docs and
  _db_updates. Some others extensions are available in the refuge projects.

* Build and run 
Download the Erlang install file from [[http://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_16.b~ubuntu~lucid_amd64.deb][here]].
#  http://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_15.b~ubuntu~oneiric_amd64.deb
 
and put it in the rcouch Dockerfile directory.

You will need to run the [[https://github.com/Michieljoris/Dockerfiles/tree/master/supervisor][supervisor]] Dockerfile as well, since this image is
based on it.

=bin/build= to build the michieljoris/rcouch image.

=bin/run= to run the rcouch container.

=docker stop rcouch= to pause the container

=docker start rcouch= to start the container up again.

=bin/reset= to reset the container to its beginning state (rcouch db is empty
again).

Access =rcouch= on http://localhost:5984


* Todo
- cleanup image, minimize image
- run as rcouch user  
- verify source?  
- build standalone rcouch and make minimal image 
- ssl version? 
  

  
  
  
 
